--IO 操作
file = io.open("/Users/damon/Desktop/Lua_Project/test.lua","r")
io.input(file)
print(io.read())
io.close(file)
--以附件的方法打开文件，如果该文件不存在则创建，否则直接把文本添加尾部
test=io.open("/Users/damon/Desktop/Lua_Project/test.txt","a")
io.output(test)
io.write("this is test")
io.close(test)
test01=io.open("/Users/damon/Desktop/Lua_Project/test1.txt","a")
io.input(test01)
io.output(test01)
io.write("this is test01 \n")
print(io.read())
io.close(test01)
test02=io.open("/Users/damon/Desktop/Lua_Project/mylua.lua","r")
io.input(test02)
io.output(test02)
print(io.read("*a"))
io.close(test02)